services:
  item-lending-api:
    build: .
    container_name: logistics-item-lending-api
    ports:
      - "8011:8011"
    volumes:
      - item-lending-data:/data
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
    restart: unless-stopped

volumes:
  item-lending-data:
    name: logistics-item-lending-data
